import { ECISControl, ECISv8Control } from '@/types/quantificationForm';
import { CisCode } from './cisControls';

export type CISV8Code = Exclude<CisCode, '19' | '20'>;

export const CONTROL_CODE_MAP_DESC = {
  '1': {
    title: 'Inventory and Control of Enterprise Assets',
    desc: 'Actively manage (inventory, track, and correct) all enterprise assets (end-user devices, including portable and mobile; network devices; non-computing/Internet of Things (IoT) devices; and servers) connected to the infrastructure physically, virtually, remotely, and those within cloud environments, to accurately know the totality of assets that need to be monitored and protected within the enterprise. This will also support identifying unauthorized and unmanaged assets to remove or remediate.',
    abbr: 'ICEA',
    category: 'vendorsInventory',
    controlNumber: 1,
    safeguards: [
      {
        title: 'Establish and Maintain Detailed Enterprise Asset Inventory',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '1.1',
      },
      {
        title: 'Address Unauthorized Assets',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Respond',
        ig: [1, 1, 1],
        index: '1.2',
      },
      {
        title: 'Utilize an Active Discovery Tool',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '1.3',
      },
      {
        title:
          'Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '1.4',
      },
      {
        title: 'Use a Passive Asset Discovery Tool',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 0, 1],
        index: '1.5',
      },
    ],
  },
  '2': {
    title: 'Inventory and Control of Software Assets',
    desc: 'Actively manage (inventory, track, and correct) all software (operating systems and applications) on the network so that only authorized software is installed and can execute, and that unauthorized and unmanaged software is found and prevented from installation or execution.',
    abbr: 'ICSA',
    category: 'vendorsInventory',
    controlNumber: 2,
    safeguards: [
      {
        title: 'Establish and Maintain a Software Inventory',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '2.1',
      },
      {
        title: 'Ensure Authorized Software is Currently Supported ',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '2.2',
      },
      {
        title: 'Address Unauthorized Software',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Respond',
        ig: [1, 1, 1],
        index: '2.3',
      },
      {
        title: 'Utilize Automated Software Inventory Tools',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '2.4',
      },
      {
        title: 'Allowlist Authorized Software',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '2.5',
      },
      {
        title: 'Allowlist Authorized Libraries',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '2.6',
      },
      {
        title: 'Allowlist Authorized Scripts',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '2.7',
      },
    ],
  },
  '3': {
    title: 'Data Protection',
    desc: 'Develop processes and technical controls to identify, classify, securely handle, retain, and dispose of data.',
    abbr: 'DP',
    category: 'protectiveMeasures',
    controlNumber: 3,
    safeguards: [
      {
        title: 'Establish and Maintain a Data Management Process',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '3.1',
      },
      {
        title: 'Establish and Maintain a Data Inventory',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '3.2',
      },
      {
        title: 'Configure Data Access Control Lists',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '3.3',
      },
      {
        title: 'Enforce Data Retention',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '3.4',
      },
      {
        title: 'Securely Dispose of Data',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '3.5',
      },
      {
        title: 'Encrypt Data on End-User Devices',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '3.6',
      },
      {
        title: 'Establish and Maintain a Data Classification Scheme',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '3.7',
      },
      {
        title: 'Document Data Flows',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '3.8',
      },
      {
        title: 'Encrypt Data on Removable Media',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '3.9',
      },
      {
        title: 'Encrypt Sensitive Data in Transit',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '3.10',
      },
      {
        title: 'Encrypt Sensitive Data at Rest',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '3.11',
      },
      {
        title: 'Segment Data Processing and Storage Based on Sensitivity',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '3.12',
      },
      {
        title: 'Deploy a Data Loss Prevention Solution',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '3.13',
      },
      {
        title: 'Log Sensitive Data Access',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 0, 1],
        index: '3.14',
      },
    ],
  },
  '4': {
    title: 'Secure Configuration of Enterprise Assets and Software',
    desc: 'Establish and maintain the secure configuration of enterprise assets (end-user devices, including portable and mobile; network devices; non-computing/IoT devices; and servers) and software (operating systems and applications).',
    abbr: 'SCEAS',
    category: 'securityAwareness',
    controlNumber: 4,
    safeguards: [
      {
        title: 'Establish and Maintain a Secure Configuration Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '4.1',
      },
      {
        title:
          'Establish and Maintain a Secure Configuration Process for Network Infrastructure',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '4.2',
      },
      {
        title: 'Configure Automatic Session Locking on Enterprise Assets',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '4.3',
      },
      {
        title: 'Implement and Manage a Firewall on Servers',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '4.4',
      },
      {
        title: 'Implement and Manage a Firewall on End-User Devices',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '4.5',
      },
      {
        title: 'Securely Manage Enterprise Assets and Software',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '4.6',
      },
      {
        title: 'Manage Default Accounts on Enterprise Assets and Software',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '4.7',
      },
      {
        title:
          'Uninstall or Disable Unnecessary Services on Enterprise Assets and Software',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '4.8',
      },
      {
        title: 'Configure Trusted DNS Servers on Enterprise Assets',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '4.9',
      },
      {
        title: 'Enforce Automatic Device Lockout on Portable End-User Devices',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '4.10',
      },
      {
        title: 'Enforce Remote Wipe Capability on Portable End-User Devices',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '4.11',
      },
      {
        title: 'Separate Enterprise Workspaces on Mobile End-User Devices',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '4.12',
      },
    ],
  },
  '5': {
    title: 'Account Management',
    desc: 'Use processes and tools to assign and manage authorization to credentials for user accounts, including administrator accounts, as well as service accounts, to enterprise assets and software.',
    abbr: 'AM',
    category: 'identityControl',
    controlNumber: 5,
    safeguards: [
      {
        title: 'Establish and Maintain an Inventory of Accounts',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '5.1',
      },
      {
        title: 'Use Unique Passwords',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '5.2',
      },
      {
        title: 'Disable Dormant Accounts',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '5.3',
      },
      {
        title:
          'Restrict Administrator Privileges to Dedicated Administrator Accounts',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '5.4',
      },
      {
        title: 'Establish and Maintain an Inventory of Service Accounts',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '5.5',
      },
      {
        title: 'Centralize Account Management',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '5.6',
      },
    ],
  },
  '6': {
    title: 'Access Control Management',
    desc: 'Use processes and tools to create, assign, manage, and revoke access credentials and privileges for user, administrator, and service accounts for enterprise assets and software.',
    abbr: 'ACM',
    category: 'identityControl',
    controlNumber: 6,
    safeguards: [
      {
        title: 'Establish an Access Granting Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '6.1',
      },
      {
        title: 'Establish an Access Revoking Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '6.2',
      },
      {
        title: 'Require MFA for Externally-Exposed Applications',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '6.3',
      },
      {
        title: 'Require MFA for Remote Network Access',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '6.4',
      },
      {
        title: 'Require MFA for Administrative Access',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '6.5',
      },
      {
        title:
          'Establish and Maintain an Inventory of Authentication and Authorization Systems',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '6.6',
      },
      {
        title: 'Centralize Access Control',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '6.7',
      },
      {
        title: 'Define and Maintain Role-Based Access Control',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 0, 1],
        index: '6.8',
      },
    ],
  },
  '7': {
    title: 'Continuous Vulnerability Management',
    desc: "Develop a plan to continuously assess and track vulnerabilities on all enterprise assets within the enterprise's infrastructure, in order to remediate, and minimize, the window of opportunity for attackers. Monitor public and private industry sources for new threat and vulnerability information.",
    abbr: 'CVM',
    category: 'threatHandling',
    controlNumber: 7,
    safeguards: [
      {
        title: 'Establish and Maintain a Vulnerability Management Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '7.1',
      },
      {
        title: 'Establish and Maintain a Remediation Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '7.2',
      },
      {
        title: 'Perform Automated Operating System Patch Management',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '7.3',
      },
      {
        title: 'Perform Automated Application Patch Management',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '7.4',
      },
      {
        title:
          'Perform Automated Vulnerability Scans of Internal Enterprise Assets',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '7.5',
      },
      {
        title:
          'Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '7.6',
      },
      {
        title: 'Remediate Detected Vulnerabilities',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Respond',
        ig: [0, 1, 1],
        index: '7.7',
      },
    ],
  },
  '8': {
    title: 'Audit Log Management',
    desc: 'Collect, alert, review, and retain audit logs of events that could help detect, understand, or recover from an attack.',
    abbr: 'ALM',
    category: 'incidentResponseManagement',
    controlNumber: 8,
    safeguards: [
      {
        title: 'Establish and Maintain an Audit Log Management Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '8.1',
      },
      {
        title: 'Collect Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [1, 1, 1],
        index: '8.2',
      },
      {
        title: 'Ensure Adequate Audit Log Storage',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '8.3',
      },
      {
        title: 'Standardize Time Synchronization',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '8.4',
      },
      {
        title: 'Collect Detailed Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.5',
      },
      {
        title: 'Collect DNS Query Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.6',
      },
      {
        title: 'Collect URL Request Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.7',
      },
      {
        title: 'Collect Command-Line Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.8',
      },
      {
        title: 'Centralize Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.9',
      },
      {
        title: 'Retain Audit Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '8.10',
      },
      {
        title: 'Conduct Audit Log Reviews',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '8.11',
      },
      {
        title: 'Collect Service Provider Logs',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 0, 1],
        index: '8.12',
      },
    ],
  },
  '9': {
    title: 'Email and Web Browser Protections',
    desc: 'Improve protections and detections of threats from email and web vectors, as these are opportunities for attackers to manipulate human behavior through direct engagement.',
    abbr: 'EWBP',
    category: 'protectiveMeasures',
    controlNumber: 9,
    safeguards: [
      {
        title: 'Ensure Use of Only Fully Supported Browsers and Email Clients',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '9.1',
      },
      {
        title: 'Use DNS Filtering Services',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '9.2',
      },
      {
        title: 'Maintain and Enforce Network-Based URL Filters',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '9.3',
      },
      {
        title:
          'Restrict Unnecessary or Unauthorized Browser and Email Client Extensions',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '9.4',
      },
      {
        title: 'Implement DMARC',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '9.5',
      },
      {
        title: 'Block Unnecessary File Types',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '9.6',
      },
      {
        title: 'Deploy and Maintain Email Server Anti-Malware Protections',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '9.7',
      },
    ],
  },
  '10': {
    title: 'Malware Defenses',
    desc: 'Prevent or control the installation, spread, and execution of malicious applications, code, or scripts on enterprise assets.',
    abbr: 'MD',
    category: 'protectiveMeasures',
    controlNumber: 10,
    safeguards: [
      {
        title: 'Deploy and Maintain Anti-Malware Software',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [1, 1, 1],
        index: '10.1',
      },
      {
        title: 'Configure Automatic Anti-Malware Signature Updates',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '10.2',
      },
      {
        title: 'Disable Autorun and Autoplay for Removable Media',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '10.3',
      },
      {
        title: 'Configure Automatic Anti-Malware Scanning of Removable Media',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '10.4',
      },
      {
        title: 'Enable Anti-Exploitation Features',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '10.5',
      },
      {
        title: 'Centrally Manage Anti-Malware Software',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '10.6',
      },
      {
        title: 'Use Behavior-Based Anti-Malware Software',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '10.7',
      },
    ],
  },
  '11': {
    title: 'Data Recovery',
    desc: 'Establish and maintain data recovery practices sufficient to restore in-scope enterprise assets to a pre-incident and trusted state.',
    abbr: 'DR',
    category: 'incidentResponseManagement',
    controlNumber: 11,
    safeguards: [
      {
        title: 'Establish and Maintain a Data Recovery Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '11.1',
      },
      {
        title: 'Perform Automated Backups',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Recover',
        ig: [1, 1, 1],
        index: '11.2',
      },
      {
        title: 'Protect Recovery Data',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '11.3',
      },
      {
        title: 'Establish and Maintain an Isolated Instance of Recovery Data',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Recover',
        ig: [1, 1, 1],
        index: '11.4',
      },
      {
        title: 'Test Data Recovery',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Recover',
        ig: [0, 1, 1],
        index: '11.5',
      },
    ],
  },
  '12': {
    title: 'Network Infrastructure Management',
    desc: 'Establish, implement, and actively manage (track, report, correct) network devices, in order to prevent attackers from exploiting vulnerable network services and access points.',
    abbr: 'NIM',
    category: 'vendorsInventory',
    controlNumber: 12,
    safeguards: [
      {
        title: 'Ensure Network Infrastructure is Up-to-Date',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '12.1',
      },
      {
        title: 'Establish and Maintain a Secure Network Architecture',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '12.2',
      },
      {
        title: 'Securely Manage Network Infrastructure',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '12.3',
      },
      {
        title: 'Establish and Maintain Architecture Diagram(s)',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '12.4',
      },
      {
        title:
          'Centralize Network Authentication, Authorization, and Auditing (AAA)',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '12.5',
      },
      {
        title: 'Use of Secure Network Management and Communication Protocols',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '12.6',
      },
      {
        title:
          'Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise\\u2019s AAA Infrastructure',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '12.7',
      },
      {
        title:
          'Establish and Maintain Dedicated Computing Resources for All Administrative Work',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '12.8',
      },
    ],
  },
  '13': {
    title: 'Network Monitoring and Defense',
    desc: "Operate processes and tooling to establish and maintain comprehensive network monitoring and defense against security threats across the enterprise's network infrastructure and user base.",
    abbr: 'NMD',
    category: 'protectiveMeasures',
    controlNumber: 13,
    safeguards: [
      {
        title: 'Centralize Security Event Alerting',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '13.1',
      },
      {
        title: 'Deploy a Host-Based Intrusion Detection Solution',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '13.2',
      },
      {
        title: 'Deploy a Network Intrusion Detection Solution',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '13.3',
      },
      {
        title: 'Perform Traffic Filtering Between Network Segments',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '13.4',
      },
      {
        title: 'Manage Access Control for Remote Assets',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '13.5',
      },
      {
        title: 'Collect Network Traffic Flow Logs ',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '13.6',
      },
      {
        title: 'Deploy a Host-Based Intrusion Prevention Solution',
        assetType: 'Devices',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '13.7',
      },
      {
        title: 'Deploy a Network Intrusion Prevention Solution',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '13.8',
      },
      {
        title: 'Deploy Port-Level Access Control',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '13.9',
      },
      {
        title: 'Perform Application Layer Filtering',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '13.10',
      },
      {
        title: 'Tune Security Event Alerting Thresholds',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 0, 1],
        index: '13.11',
      },
    ],
  },
  '14': {
    title: 'Security Awareness and Skills Training',
    desc: 'Establish and maintain a security awareness program to influence behavior among the workforce to be security conscious and properly skilled to reduce cybersecurity risks to the enterprise.',
    abbr: 'SAST',
    category: 'securityAwareness',
    controlNumber: 14,
    safeguards: [
      {
        title: 'Establish and Maintain a Security Awareness Program',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '14.1',
      },
      {
        title:
          'Train Workforce Members to Recognize Social Engineering Attacks',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.2',
      },
      {
        title: 'Train Workforce Members on Authentication Best Practices',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.3',
      },
      {
        title: 'Train Workforce on Data Handling Best Practices',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.4',
      },
      {
        title:
          'Train Workforce Members on Causes of Unintentional Data Exposure',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.5',
      },
      {
        title:
          'Train Workforce Members on Recognizing and Reporting Security Incidents',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.6',
      },
      {
        title:
          'Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.7',
      },
      {
        title:
          'Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [1, 1, 1],
        index: '14.8',
      },
      {
        title: 'Conduct Role-Specific Security Awareness and Skills Training',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '14.9',
      },
    ],
  },
  '15': {
    title: 'Service Provider Management',
    desc: "Develop a process to evaluate service providers who hold sensitive data, or are responsible for an enterprise's critical IT platforms or processes, to ensure these providers are protecting those platforms and data appropriately.",
    abbr: 'SPM',
    category: 'vendorsInventory',
    controlNumber: 15,
    safeguards: [
      {
        title: 'Establish and Maintain an Inventory of Service Providers',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Identify',
        ig: [1, 1, 1],
        index: '15.1',
      },
      {
        title: 'Establish and Maintain a Service Provider Management Policy',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '15.2',
      },
      {
        title: 'Classify Service Providers',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '15.3',
      },
      {
        title:
          'Ensure Service Provider Contracts Include Security Requirements',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '15.4',
      },
      {
        title: 'Assess Service Providers',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 0, 1],
        index: '15.5',
      },
      {
        title: 'Monitor Service Providers',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 0, 1],
        index: '15.6',
      },
      {
        title: 'Securely Decommission Service Providers',
        assetType: 'Data',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '15.7',
      },
    ],
  },
  '16': {
    title: 'Application Software Security',
    desc: 'Manage the security life cycle of in-house developed, hosted, or acquired software to prevent, detect, and remediate security weaknesses before they can impact the enterprise.',
    abbr: 'ASS',
    category: 'protectiveMeasures',
    controlNumber: 16,
    safeguards: [
      {
        title: 'Establish and Maintain a Secure Application DevelopmentProcess',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '16.1',
      },
      {
        title:
          'Establish and Maintain a Process to Accept and Address Software Vulnerabilities',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '16.2',
      },
      {
        title: 'Perform Root Cause Analysis on Security Vulnerabilities',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.3',
      },
      {
        title:
          'Establish and Manage an Inventory of Third-Party Software Components',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '16.4',
      },
      {
        title: 'Use Up-to-Date and Trusted Third-Party Software Components',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.5',
      },
      {
        title:
          'Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '16.6',
      },
      {
        title:
          'Use Standard Hardening Configuration Templates for Application Infrastructure',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.7',
      },
      {
        title: 'Separate Production and Non-Production Systems',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.8',
      },
      {
        title:
          'Train Developers in Application Security Concepts and Secure Coding',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.9',
      },
      {
        title: 'Apply Secure Design Principles in Application Architectures',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '16.10',
      },
      {
        title:
          'Leverage Vetted Modules or Services for Application Security Components',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Identify',
        ig: [0, 1, 1],
        index: '16.11',
      },
      {
        title: 'Implement Code-Level Security Checks',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '16.12',
      },
      {
        title: 'Conduct Application Penetration Testing',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 0, 1],
        index: '16.13',
      },
      {
        title: 'Conduct Threat Modeling',
        assetType: 'Software',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '16.14',
      },
    ],
  },
  '17': {
    title: 'Incident Response Management',
    desc: 'Establish a program to develop and maintain an incident response capability (e.g., policies, plans, procedures, defined roles, training, and communications) to prepare, detect, and quickly respond to an attack.',
    abbr: 'IRM',
    category: 'incidentResponseManagement',
    controlNumber: 17,
    safeguards: [
      {
        title: 'Designate Personnel to Manage Incident Handling',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Respond',
        ig: [1, 1, 1],
        index: '17.1',
      },
      {
        title:
          'Establish and Maintain Contact Information for Reporting Security Incidents',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '17.2',
      },
      {
        title:
          'Establish and Maintain an Enterprise Process for Reporting Incidents',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [1, 1, 1],
        index: '17.3',
      },
      {
        title: 'Establish and Maintain an Incident Response Process',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '17.4',
      },
      {
        title: 'Assign Key Roles and Responsibilities',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Respond',
        ig: [0, 1, 1],
        index: '17.5',
      },
      {
        title: 'Define Mechanisms for Communicating During Incident Response',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Respond',
        ig: [0, 1, 1],
        index: '17.6',
      },
      {
        title: 'Conduct Routine Incident Response Exercises',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Recover',
        ig: [0, 1, 1],
        index: '17.7',
      },
      {
        title: 'Conduct Post-Incident Reviews',
        assetType: 'Users',
        desc: '',
        securityFunction: 'Recover',
        ig: [0, 1, 1],
        index: '17.8',
      },
      {
        title: 'Establish and Maintain Security Incident Thresholds',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Recover',
        ig: [0, 0, 1],
        index: '17.9',
      },
    ],
  },
  '18': {
    title: 'Penetration Testing',
    desc: 'Test the effectiveness and resiliency of enterprise assets through identifying and exploiting weaknesses in controls (people, processes, and technology), and simulating the objectives and actions of an attacker.',
    abbr: 'PT',
    category: 'threatHandling',
    controlNumber: 18,
    safeguards: [
      {
        title: 'Establish and Maintain a Penetration Testing Program',
        assetType: 'Documentation',
        desc: '',
        securityFunction: 'Govern',
        ig: [0, 1, 1],
        index: '18.1',
      },
      {
        title: 'Perform Periodic External Penetration Tests',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 1, 1],
        index: '18.2',
      },
      {
        title: 'Remediate Penetration Test Findings',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 1, 1],
        index: '18.3',
      },
      {
        title: 'Validate Security Measures',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Protect',
        ig: [0, 0, 1],
        index: '18.4',
      },
      {
        title: 'Perform Periodic Internal Penetration Tests',
        assetType: 'Network',
        desc: '',
        securityFunction: 'Detect',
        ig: [0, 0, 1],
        index: '18.5',
      },
    ],
  },
} as const;

export const CisV8SafeguardsByAbbr = {
  ICEA: ['ICEA-1', 'ICEA-2', 'ICEA-3', 'ICEA-4', 'ICEA-5'],
  ICSA: ['ICSA-1', 'ICSA-2', 'ICSA-3', 'ICSA-4', 'ICSA-5', 'ICSA-6', 'ICSA-7'],
  DP: [
    'DP-1',
    'DP-2',
    'DP-3',
    'DP-4',
    'DP-5',
    'DP-6',
    'DP-7',
    'DP-8',
    'DP-9',
    'DP-10',
    'DP-11',
    'DP-12',
    'DP-13',
    'DP-14',
  ],
  SCEAS: [
    'SCEAS-1',
    'SCEAS-2',
    'SCEAS-3',
    'SCEAS-4',
    'SCEAS-5',
    'SCEAS-6',
    'SCEAS-7',
    'SCEAS-8',
    'SCEAS-9',
    'SCEAS-10',
    'SCEAS-11',
    'SCEAS-12',
  ],
  AM: ['AM-1', 'AM-2', 'AM-3', 'AM-4', 'AM-5', 'AM-6'],
  ACM: ['ACM-1', 'ACM-2', 'ACM-3', 'ACM-4', 'ACM-5', 'ACM-6', 'ACM-7', 'ACM-8'],
  CVM: ['CVM-1', 'CVM-2', 'CVM-3', 'CVM-4', 'CVM-5', 'CVM-6', 'CVM-7'],
  ALM: [
    'ALM-1',
    'ALM-2',
    'ALM-3',
    'ALM-4',
    'ALM-5',
    'ALM-6',
    'ALM-7',
    'ALM-8',
    'ALM-9',
    'ALM-10',
    'ALM-11',
    'ALM-12',
  ],
  EWBP: ['EWBP-1', 'EWBP-2', 'EWBP-3', 'EWBP-4', 'EWBP-5', 'EWBP-6', 'EWBP-7'],
  MD: ['MD-1', 'MD-2', 'MD-3', 'MD-4', 'MD-5', 'MD-6', 'MD-7'],
  DR: ['DR-1', 'DR-2', 'DR-3', 'DR-4', 'DR-5'],
  NIM: ['NIM-1', 'NIM-2', 'NIM-3', 'NIM-4', 'NIM-5', 'NIM-6', 'NIM-7', 'NIM-8'],
  NMD: [
    'NMD-1',
    'NMD-2',
    'NMD-3',
    'NMD-4',
    'NMD-5',
    'NMD-6',
    'NMD-7',
    'NMD-8',
    'NMD-9',
    'NMD-10',
    'NMD-11',
  ],
  SAST: [
    'SAST-1',
    'SAST-2',
    'SAST-3',
    'SAST-4',
    'SAST-5',
    'SAST-6',
    'SAST-7',
    'SAST-8',
    'SAST-9',
  ],
  SPM: ['SPM-1', 'SPM-2', 'SPM-3', 'SPM-4', 'SPM-5', 'SPM-6', 'SPM-7'],
  ASS: [
    'ASS-1',
    'ASS-2',
    'ASS-3',
    'ASS-4',
    'ASS-5',
    'ASS-6',
    'ASS-7',
    'ASS-8',
    'ASS-9',
    'ASS-10',
    'ASS-11',
    'ASS-12',
    'ASS-13',
    'ASS-14',
  ],
  IRM: [
    'IRM-1',
    'IRM-2',
    'IRM-3',
    'IRM-4',
    'IRM-5',
    'IRM-6',
    'IRM-7',
    'IRM-8',
    'IRM-9',
  ],
  PT: ['PT-1', 'PT-2', 'PT-3', 'PT-4', 'PT-5'],
} as const;

export type CisV8SafeguardsImplementation = {
  [key in keyof typeof CisV8SafeguardsByAbbr]: Record<
    (typeof CisV8SafeguardsByAbbr)[key][number],
    number
  >;
};

export type CisV8Abbreviation =
  (typeof CONTROL_CODE_MAP_DESC)[CISV8Code]['abbr'];

export const cisV8Abbreviations = Object.values(CONTROL_CODE_MAP_DESC).map(
  ({ abbr }) => abbr,
);

const BATTERY_OPTION_COLOR = 'fill.brand.primary';
export const BY_MATURITY_BATTERY_OPTIONS = [
  {
    value: ECISv8Control.NOT_IMPLEMENTED.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
    translationKey: 'notImplemented',
  },
  {
    value: ECISv8Control.MINIMALLY.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
    translationKey: 'minimally',
  },
  {
    value: ECISv8Control.PARTIALLY.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
    translationKey: 'partially',
  },
  {
    value: ECISv8Control.MOSTLY.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
    translationKey: 'mostly',
  },
  {
    value: ECISv8Control.FULLY.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
    translationKey: 'fully',
  },
];
export const BY_THEME_BATTERY_OPTIONS = [
  {
    value: ECISControl.NOT_IMPLEMENTED.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
  },
  {
    value: ECISControl.IG1.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
  },
  {
    value: ECISControl.IG2.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
  },
  {
    value: ECISControl.IG3.toString(),
    backgroundColor: BATTERY_OPTION_COLOR,
  },
];

const getControlAbbrByTheme = <T extends readonly string[]>(
  controlCodes: T,
): string[] => {
  const controls = Object.fromEntries(
    Object.entries(CONTROL_CODE_MAP_DESC).filter(([k]) =>
      (controlCodes as readonly string[]).includes(k),
    ),
  );
  return Object.values(controls).map((item) => item.abbr);
};

export const assetsAndVendorsInventoryControlsCodes = [
  '1',
  '2',
  '12',
  '15',
] as const;
export const ASSETS_AND_VENDORS_INVENTORY_ABBR = getControlAbbrByTheme(
  assetsAndVendorsInventoryControlsCodes,
);

export const accessAndIdentityControlsCodes = ['5', '6'] as const;
export const ACCESS_AND_IDENTITY_ABBR = getControlAbbrByTheme(
  accessAndIdentityControlsCodes,
);

export const threatAndVulnerabilityControlsCodes = ['7', '18'] as const;
export const THREAT_AND_VULNERABILITY_ABBR = getControlAbbrByTheme(
  threatAndVulnerabilityControlsCodes,
);

export const protectiveMeasuresAndDefensesControlsCodes = [
  '3',
  '9',
  '10',
  '13',
  '16',
] as const;
export const PROTECTIVE_MEASURES_AND_DEFENSES_ABBR = getControlAbbrByTheme(
  protectiveMeasuresAndDefensesControlsCodes,
);

export const securityAwarenessAndTrainingControlsCodes = ['4', '14'] as const;
export const SECURITY_AWARENESS_AND_TRAINING_ABBR = getControlAbbrByTheme(
  securityAwarenessAndTrainingControlsCodes,
);

export const incidentResponseManagementControlsCodes = [
  '8',
  '11',
  '17',
] as const;
export const INCIDENT_RESPONSE_MANAGEMENT_ABBR = getControlAbbrByTheme(
  incidentResponseManagementControlsCodes,
);

export const cisV8AbbrToCode = (abbr: CisV8Abbreviation): CISV8Code => {
  const data = Object.entries(CONTROL_CODE_MAP_DESC).find(
    ([_, item]) => item.abbr === abbr,
  );
  return data![0] as CISV8Code;
};

// Returns the titles for a given safeguard
export const abbrToText = (abbr: string): Record<string, any> => {
  try {
    const [controlAbbr, controlNumberRaw] = abbr.split('-');
    const controlNumber = parseInt(controlNumberRaw);
    const safeguards = Object.values(CONTROL_CODE_MAP_DESC).find(
      (item) => item.abbr === controlAbbr,
    )?.safeguards;
    if (!safeguards) {
      return {
        title: abbr,
        secondaryTitle: abbr,
        desc: abbr,
      };
    }
    const safeguard = safeguards[controlNumber - 1];
    return {
      title: abbr,
      secondaryTitle: safeguard.title,
      desc: safeguard.desc,
    };
  } catch (error) {
    console.error(error);
    return {
      title: abbr,
      secondaryTitle: abbr,
      desc: abbr,
    };
  }
};
