export type ScenarioEnumItem = {
  name: string;
  value: string;
};

export const scenarioEnums = {
  scenarioTypes: [
    { name: 'MANUAL', value: 'manual' },
    { name: 'CRQ', value: 'crq' },
  ],
  scenarioStatuses: [
    { name: 'PENDING', value: 'pending' },
    { name: 'IN_PROGRESS', value: 'in_progress' },
    { name: 'COMPLETED', value: 'completed' },
  ],
  likelihood: [
    { name: 'Expected', value: 'Expected' },
    { name: 'Likely', value: 'Likely' },
    { name: 'Possible', value: 'Possible' },
    { name: 'Unlikely', value: 'Unlikely' },
    { name: 'Rare', value: 'Rare' },
  ],
  impact: [
    { name: 'Severe', value: 'Severe' },
    { name: 'Significant', value: 'Significant' },
    { name: 'Moderate', value: 'Moderate' },
    { name: 'Minor', value: 'Minor' },
    { name: 'Negligible', value: 'Negligible' },
  ],
  riskPriority: [
    { name: 'Critical', value: 'Critical' },
    { name: 'High', value: 'High' },
    { name: 'Medium', value: 'Medium' },
    { name: 'Low', value: 'Low' },
  ],
  responsePlan: [
    { name: 'Accept', value: 'Accept' },
    { name: 'Avoid', value: 'Avoid' },
    { name: 'Mitigate', value: 'Mitigate' },
    { name: 'Transfer', value: 'Transfer' },
  ],
  scenarioCategory: [
    { name: 'STRATEGIC_RISK', value: 'Strategic Risk' },
    { name: 'OPERATIONAL_RISK', value: 'Operational Risk' },
    { name: 'TECHNICAL_RISK', value: 'Technical Risk' },
    { name: 'PRIVACY_RISK', value: 'Privacy Risk' },
    { name: 'SECURITY_RISK', value: 'Security Risk' },
    { name: 'ETHICAL_RISK', value: 'Ethical Risk' },
    { name: 'FAIRNESS_BIAS_RISK', value: 'Fairness/Bias Risk' },
    { name: 'LEGAL_COMPLIANCE_RISK', value: 'Legal/Compliance Risk' },
    { name: 'SAFETY_RISK', value: 'Safety Risk' },
    { name: 'REPUTATIONAL_RISK', value: 'Reputational Risk' },
    { name: 'ENVIRONMENTAL_RISK', value: 'Environmental Risk' },
  ],
  scenarioTactic: [
    { name: 'DRIVE_BY_COMPROMISE', value: 'Drive-by Compromise (AML.T0078)' },
    {
      name: 'EXPLOIT_PUBLIC_FACING_APPLICATION',
      value: 'Exploit Public-Facing Application (AML.T0049)',
    },
    { name: 'PHISHING', value: 'Phishing (AML.T0052)' },
    {
      name: 'PHISHING_SPEARPHISHING_SOCIAL_ENGINEERING_LLM',
      value: 'Phishing: Spearphishing via Social Engineering LLM (AML.T0052.000)',
    },
    { name: 'AI_SUPPLY_CHAIN_COMPROMISE', value: 'AI Supply Chain Compromise (AML.T0010)' },
    {
      name: 'AI_SUPPLY_CHAIN_COMPROMISE_HARDWARE',
      value: 'AI Supply Chain Compromise: Hardware (AML.T0010.000)',
    },
    {
      name: 'AI_SUPPLY_CHAIN_COMPROMISE_AI_SOFTWARE',
      value: 'AI Supply Chain Compromise: AI Software (AML.T0010.001)',
    },
    {
      name: 'AI_SUPPLY_CHAIN_COMPROMISE_DATA',
      value: 'AI Supply Chain Compromise: Data (AML.T0010.002)',
    },
    {
      name: 'AI_SUPPLY_CHAIN_COMPROMISE_MODEL',
      value: 'AI Supply Chain Compromise: Model (AML.T0010.003)',
    },
    {
      name: 'AI_SUPPLY_CHAIN_COMPROMISE_CONTAINER_REGISTRY',
      value: 'AI Supply Chain Compromise: Container Registry (AML.T0010.004)',
    },
    { name: 'VALID_ACCOUNTS', value: 'Valid Accounts (AML.T0012)' },
    { name: 'EVADE_AI_MODEL', value: 'Evade AI Model (AML.T0015)' },
  ],
  scenarioEventType: [
    { name: 'DATA_EXFILTRATION', value: 'Data Exfiltration' },
    { name: 'MODEL_INTEGRITY', value: 'Model Integrity' },
    { name: 'MODEL_AVAILABILITY', value: 'Model Availability' },
    { name: 'MODEL_WASTAGE', value: 'Model Wastage' },
  ],
  scenarioImpactType: [
    { name: 'FINANCIAL_LOSS', value: 'Financial Loss' },
    { name: 'PHYSICAL_HARM', value: 'Physical Harm' },
    { name: 'PSYCHOLOGICAL_HARM', value: 'Psychological Harm' },
    { name: 'DISCRIMINATION', value: 'Discrimination' },
    { name: 'PRIVACY_VIOLATION', value: 'Privacy Violation' },
    { name: 'REPUTATIONAL_DAMAGE', value: 'Reputational Damage' },
    { name: 'REGULATORY_NON_COMPLIANCE', value: 'Regulatory Non-Compliance' },
    { name: 'ENVIRONMENTAL_DAMAGE', value: 'Environmental Damage' },
    { name: 'LOSS_OF_TRUST', value: 'Loss of Trust' },
    { name: 'OPERATIONAL_DISRUPTION', value: 'Operational Disruption' },
    { name: 'DATA_BREACH', value: 'Data Breach' },
    { name: 'HUMAN_RIGHTS_VIOLATION', value: 'Human Rights Violation' },
  ],
  aiAsset: [
    { name: 'OPENAI_GPT_4_TURBO', value: 'OpenAI - GPT-4 Turbo' },
    { name: 'OPENAI_GPT_4', value: 'OpenAI - GPT-4' },
    { name: 'OPENAI_GPT_3_5_TURBO', value: 'OpenAI - GPT-3.5 Turbo' },
    { name: 'OPENAI_GPT_3_5', value: 'OpenAI - GPT-3.5' },
    { name: 'OPENAI_DALL_E_3', value: 'OpenAI - DALL-E 3' },
    { name: 'OPENAI_DALL_E_2', value: 'OpenAI - DALL-E 2' },
    { name: 'OPENAI_WHISPER', value: 'OpenAI - Whisper' },
    { name: 'OPENAI_TEXT_TO_SPEECH', value: 'OpenAI - Text-to-Speech (TTS)' },
    { name: 'OPENAI_GPT_4_VISION', value: 'OpenAI - GPT-4 Vision' },
    { name: 'ANTHROPIC_CLAUDE_3_5_SONNET', value: 'Anthropic - Claude 3.5 Sonnet' },
    { name: 'ANTHROPIC_CLAUDE_3_OPUS', value: 'Anthropic - Claude 3 Opus' },
    { name: 'ANTHROPIC_CLAUDE_3_SONNET', value: 'Anthropic - Claude 3 Sonnet' },
    { name: 'ANTHROPIC_CLAUDE_3_HAIKU', value: 'Anthropic - Claude 3 Haiku' },
    { name: 'ANTHROPIC_CLAUDE_2_1', value: 'Anthropic - Claude 2.1' },
    { name: 'ANTHROPIC_CLAUDE_2_0', value: 'Anthropic - Claude 2.0' },
    { name: 'ANTHROPIC_CLAUDE_INSTANT', value: 'Anthropic - Claude Instant' },
    { name: 'GOOGLE_GEMINI_1_5_PRO', value: 'Google - Gemini 1.5 Pro' },
    { name: 'GOOGLE_GEMINI_1_5_FLASH', value: 'Google - Gemini 1.5 Flash' },
    { name: 'GOOGLE_GEMINI_1_0_PRO', value: 'Google - Gemini 1.0 Pro' },
    { name: 'GOOGLE_GEMINI_1_0_NANO', value: 'Google - Gemini 1.0 Nano' },
    { name: 'GOOGLE_PALM_2', value: 'Google - PaLM 2' },
    { name: 'GOOGLE_BARD', value: 'Google - Bard' },
    { name: 'GOOGLE_IMAGEN_2', value: 'Google - Imagen 2' },
    { name: 'GOOGLE_MUSICLM', value: 'Google - MusicLM' },
    { name: 'META_LLAMA_3_1_405B', value: 'Meta - Llama 3.1 (405B)' },
    { name: 'META_LLAMA_3_1_70B', value: 'Meta - Llama 3.1 (70B)' },
    { name: 'META_LLAMA_3_1_8B', value: 'Meta - Llama 3.1 (8B)' },
    { name: 'META_LLAMA_3_70B', value: 'Meta - Llama 3 (70B)' },
    { name: 'META_LLAMA_3_8B', value: 'Meta - Llama 3 (8B)' },
    { name: 'META_LLAMA_2_70B', value: 'Meta - Llama 2 (70B)' },
    { name: 'META_LLAMA_2_13B', value: 'Meta - Llama 2 (13B)' },
    { name: 'META_LLAMA_2_7B', value: 'Meta - Llama 2 (7B)' },
    { name: 'META_CODE_LLAMA', value: 'Meta - Code Llama' },
    { name: 'MICROSOFT_AZURE_OPENAI_SERVICE', value: 'Microsoft - Azure OpenAI Service' },
    { name: 'MICROSOFT_PHI_3_MINI', value: 'Microsoft - Phi-3 Mini' },
    { name: 'MICROSOFT_PHI_3_SMALL', value: 'Microsoft - Phi-3 Small' },
    { name: 'MICROSOFT_PHI_3_MEDIUM', value: 'Microsoft - Phi-3 Medium' },
    { name: 'MICROSOFT_BING_CHAT', value: 'Microsoft - Bing Chat' },
    { name: 'MISTRAL_AI_MISTRAL_LARGE', value: 'Mistral AI - Mistral Large' },
    { name: 'MISTRAL_AI_MISTRAL_MEDIUM', value: 'Mistral AI - Mistral Medium' },
    { name: 'MISTRAL_AI_MISTRAL_SMALL', value: 'Mistral AI - Mistral Small' },
    { name: 'MISTRAL_AI_MISTRAL_7B', value: 'Mistral AI - Mistral 7B' },
    { name: 'MISTRAL_AI_MIXTRAL_8X7B', value: 'Mistral AI - Mixtral 8x7B' },
    { name: 'MISTRAL_AI_MIXTRAL_8X22B', value: 'Mistral AI - Mixtral 8x22B' },
    { name: 'COHERE_COMMAND_R_PLUS', value: 'Cohere - Command R+' },
    { name: 'COHERE_COMMAND_R', value: 'Cohere - Command R' },
    { name: 'COHERE_COMMAND', value: 'Cohere - Command' },
    { name: 'COHERE_COMMAND_LIGHT', value: 'Cohere - Command Light' },
    { name: 'COHERE_EMBED_V3', value: 'Cohere - Embed v3' },
    { name: 'COHERE_RERANK', value: 'Cohere - Rerank' },
    { name: 'STABILITY_AI_STABLE_DIFFUSION_XL', value: 'Stability AI - Stable Diffusion XL' },
    { name: 'STABILITY_AI_STABLE_DIFFUSION_2_1', value: 'Stability AI - Stable Diffusion 2.1' },
    { name: 'STABILITY_AI_STABLE_DIFFUSION_1_5', value: 'Stability AI - Stable Diffusion 1.5' },
    {
      name: 'STABILITY_AI_STABLE_VIDEO_DIFFUSION',
      value: 'Stability AI - Stable Video Diffusion',
    },
    { name: 'STABILITY_AI_STABLE_AUDIO', value: 'Stability AI - Stable Audio' },
    { name: 'AMAZON_TITAN_TEXT_EXPRESS', value: 'Amazon - Titan Text Express' },
    { name: 'AMAZON_TITAN_TEXT_LITE', value: 'Amazon - Titan Text Lite' },
    { name: 'AMAZON_TITAN_EMBEDDINGS', value: 'Amazon - Titan Embeddings' },
    { name: 'AMAZON_TITAN_IMAGE_GENERATOR', value: 'Amazon - Titan Image Generator' },
    {
      name: 'AMAZON_TITAN_MULTIMODAL_EMBEDDINGS',
      value: 'Amazon - Titan Multimodal Embeddings',
    },
    { name: 'XAI_GROK', value: 'xAI - Grok' },
    { name: 'XAI_GROK_1', value: 'xAI - Grok-1' },
    { name: 'INFLECTION_AI_PI', value: 'Inflection AI - Pi' },
    { name: 'AI21_LABS_JURASSIC_2_ULTRA', value: 'AI21 Labs - Jurassic-2 Ultra' },
    { name: 'AI21_LABS_JURASSIC_2_MID', value: 'AI21 Labs - Jurassic-2 Mid' },
    { name: 'AI21_LABS_JURASSIC_2_LIGHT', value: 'AI21 Labs - Jurassic-2 Light' },
  ],
} as const;

export type ScenarioEnums = typeof scenarioEnums;

export const scenarioFieldEnumValues = {
  AIAsset: scenarioEnums.aiAsset.map((item) => item.value),
  ScenarioCategory: scenarioEnums.scenarioCategory.map((item) => item.value),
  ScenarioTactic: scenarioEnums.scenarioTactic.map((item) => item.value),
  ScenarioEventType: scenarioEnums.scenarioEventType.map((item) => item.value),
  ScenarioImpactType: scenarioEnums.scenarioImpactType.map((item) => item.value),
  Likelihood: scenarioEnums.likelihood.map((item) => item.value),
  Impact: scenarioEnums.impact.map((item) => item.value),
  RiskPriority: scenarioEnums.riskPriority.map((item) => item.value),
  ResponsePlan: scenarioEnums.responsePlan.map((item) => item.value),
} as const;

export type ScenarioFieldEnumValues = typeof scenarioFieldEnumValues;


